name: Testing test-action

on: push

jobs:
  test-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: ./
        id: outputstep
      - run: echo "Who you greeted - ${{ steps.outputstep.outputs.who-you-greeted }}"
      - uses: actions/checkout@v2
      
      - name: Bump version and push tag
        run: |
          sudo apt install -y node-semver
          export currentTag=$(git tag -l --sort=-v:refname | head -n 1)
          echo "Current Tag: $currentTag"
          export commitMessage="${{ github.event.head_commit.message }}"
          echo "Commit message: $commitMessage"
          if [[ "$commitMessage" == *"#major"* ]]; then
            export finalTag="v$(semver -i major $currentTag)"
          else if [[ "$commitMessage" == *"#minor"* ]]; then
            export finalTag="v$(semver -i minor $currentTag)"
          else
            export finalTag="v$(semver -i patch $currentTag)"
          fi
          git tag $finalTag
          git tag ${finalTag%%.*} -f
          git push --tags -f