name: Testing test-action

on: push

jobs:
  test-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: ./
        id: outputstep
      - run: echo "Who you greeted - ${{ steps.outputstep.outputs.who-you-greeted }}"
      - uses: actions/checkout@v2
      
      - name: Bump version and push tag
        id: bump
        env:
          INPUT_DRY_RUN: true
        run: |
          export currentTag=$(git tag -l --sort=-v:refname | grep v* | head -n 1)
          echo "Current Tag: $currentTag"
          export commitMessage="${{ github.event.head_commit.message }}"
          echo "Commit message: $commitMessage" 
          if [[ "$commitMessage" == *"#major"* ]]; then
            export finalTag="v$(npx semver -c -i major $currentTag)"
          elif [[ "$commitMessage" == *"#minor"* ]]; then
            export finalTag="v$(npx semver -c -i minor $currentTag)"
          else
            export finalTag="v$(npx semver -c -i patch $currentTag)"
          fi
          if [[ "$finalTag" == "" ]]; then
            export finalTag="v1.0.0"
          fi
          export finalMajorVersion=${finalTag%%.*} 
          echo "::set-output name=initial-tag::$currentTag"
          echo "::set-output name=resulting-semver-tag"::$finalTag"
          echo "::set-output name=resulting-major-version::$finalMajorVersion"
          if [[ "$INPUT_DRY_RUN" == "true" ]]; then
            echo "Dry-run enabled."
            exit 0 
          fi
          git tag $finalTag
          git tag ${finalTag%%.*} -f
          git push --tags -f
      - name: Test action
        run: |
          echo "Initial: ${{ steps.bump.outputs.initial-tag }}"
          echo "Full: ${{ steps.bump.outputs.resulting-full-tag}}"
          echo "Major: ${{ steps.bump.outputs.resulting-full-tag }}"