name: Testing test-action

on: push

jobs:
  test-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: ./
        id: outputstep
      - run: echo "Who you greeted - ${{ steps.outputstep.outputs.who-you-greeted }}"
      - uses: actions/checkout@v2
      
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
