name: Testing test-action

on: push

jobs:
  test-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: outputstep
      - run: echo "Who you greeted - ${{ steps.outputs.outputstep }}"